<?php

/**
 * Theme+ - Theme extension for the Contao Open Source CMS
 *
 * Copyright (C) 2013 bit3 UG <http://bit3.de>
 *
 * @package    Theme+
 * @author     Tristan Lins <tristan.lins@bit3.de>
 * @link       http://www.themeplus.de
 * @license    http://www.gnu.org/licenses/lgpl-3.0.html LGPL
 */

namespace Bit3\Contao\ThemePlus\Asset;

use Assetic\Asset\AssetInterface;
use Assetic\Filter\FilterInterface;

/**
 * Class ConditionalAsset
 */
class ConditionalAsset
   extends AbstractDelegatorAsset
{

	/**
	 * @var array
	 */
	protected $conditions;

	public function __construct(AssetInterface $asset, $conditions)
	{
		parent::__construct($asset);
		$this->conditions = $conditions;
	}

	public function dump(FilterInterface $additionalFilter = null)
	{
		return parent::dump($additionalFilter); // TODO: Change the autogenerated stub
	}

	public function getContent()
	{
		return parent::getContent(); // TODO: Change the autogenerated stub
	}
}